# roles/postgresql/tasks/main.yml

- name: Ensure python3-apt package is installed
  apt:
    name: python3-apt
    state: present

- name: Install PostgreSQL
  apt:
    name: postgresql-{{13}}
    state: present

- name: Ensure PostgreSQL service is started
  service:
    name: postgresql
    state: started
    enabled: yes



    

