# roles/postgresql/meta/main.yml

dependencies: []
galaxy_info:
  author: Your Name
  description: Ansible role for PostgreSQL
  company: Your Company
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster

